GET http://localhost:3010/

###
POST http://localhost:3010/jobseeker/
Content-Type: application/json

{
  # "type" : "recuter11",
   "name" : "Suneel",
   "email" : "suneel123@gmail.com",
    "contactNumber":  7093041041,
   "password" : "anurag123111",
   "confirmpassword" : "anurag123111"
   
}

###
POST http://localhost:3010/recuriter/
Content-Type: application/json

{
  # "type" : "recuter11",
   "name" : "Suneel",
   "email1" : "suneel123@gmail.com",
    "contactNumber":  7093041041,
   "password" : "anurag123111",
   "confirmpassword" : "anurag123111"
   
}



###
POST http://localhost:3010/login/
Content-Type: application/json

{
    "email" : "suneel123@gmail.com",
     "password" : "anurag123111"
}

###
POST http://localhost:3010/login/
Content-Type: application/json

{
    "email1" : "suneel123@gmail.com",
     "password" : "anurag123111"
}



###
POST http://localhost:3010/profile/
Content-Type: application/json

{
  "fullname1" :"Suneel",
   "state1": "Telangana",
  "currentLocation1":"Hyderabad",
    "mobile1":"7567890088",
    "email1":"suneel1221321@mail.com"
   
}

